#%RAML 1.0 Library

uses:
    Transaction: transaction.raml

types:
    Budget:
        type: object
        description: |
            The budget is the global object containing financial data about an entity.
            This entity could be an organization, a project, a person...
        properties:
            id:
                type: string
                description: MongoDB ObjectId
                required: false
            name:
                type: string
                description: Name of the budget
                required: true
            slug:
                type: string
                description: Determined from the budget name
                required: false
            description:
                type: string
                description: Text field to put some extra informations
                required: true
            sectors:
                type: array
                description: Transaction categories
                items: Sector

    Sector:
        type: object
        description: A sector is a transaction category, gathering transaction data by thematic
        properties:
            name:
                type: string
                description: The category name
                required: true
            slug:
                type: string
                description: Determined from the sector name
                required: false
            transactions:
                type: array
                items: Transaction.Transaction
