#%RAML 1.0 Library

types:
    Transaction:
        type: object
        properties:
            id:
                type: string
                description: MongoDB ObjectId
                required: false
            wording:
                type: string
                description: The title of the transaction
                required: true
            description:
                type: string
                description: Larger text field for extra informations
                required: true
            type:
                type: string
                description: Control field to know if the transaction is an expense or an income
                enum: [expense, income]
                required: true
            amount:
                type: number
                description: The exchanged money sum
                required: true
            created_at:
                type: datetime
                description: The date of the transaction registration
                required: false
            processed_at:
                type: datetime
                description: The date of the transaction processing. Default is registration date
                required: false
